linters:
  enable:
    # - deadcode
    # - errcheck
    # - gosimple
    # - govet
    # - ineffassign
    # - staticcheck
    # - structcheck
    # - typecheck
    # - unused
    # - varcheck
    - lll
    - dupl
    - gocritic
    - gocognit
    - gocyclo
    - prealloc
    - unconvert

linters-settings:
  gocyclo:
    min-complexity: 15
  gocognit:
    min-complexity: 15
  lll:
    line-length: 185

issues:
  exclude-use-default: false
  exclude-rules:
    # Exclude some linters on test files
    - path: _test\.go
      linters:
        - lll
        - dupl
        - gocyclo
        - gocognit
        - errcheck